[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "IM-calc"
authors = [
    {name = "QuakeCoRE" },
]
version = "19.5.1"
description = "IM calculation code"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}